### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by rowpsmo1859** [JeremyBellows/elm-bootstrapify#3]
There needs to be some types for [Bootstrap Tables](http://getbootstrap.com/css/#tables)

to avoid naming conflict with `elm-lang/html`, I recommend creating the function and type

```
type TblOption -- for things like striped or bordered

tbl : List TblOption -> List (Attribute msg) -> List (Html msg) -> Html msg
```

**Comment by MazeChaZer** [comment]
I can take a look at this

**Comment by rowpsmo1859** [comment]
Excellent! Let me know if there are any questions! Thank you for contributing :)

**Comment by rowpsmo1859** [comment]
This is in 8.0.1 👍
