### ISSUE TITLE
Is navbar collapse supported?

### ISSUE THREAD

**Issue by 7sharp9** [JeremyBellows/elm-bootstrapify#4]
i.e. the collapse.js plugin is required to expand / contract the navbar:

https://getbootstrap.com/javascript/#collapse

**Comment by rowpsmo1859** [comment]
For the collapse plugin to work there needs to be some way to apply the class `collapse` to an element. [Example - 7sharp9's provided link](https://getbootstrap.com/javascript/#collapse) placed the class `collapse` on a div.) Is there any other possible elements this class would need to be attached to? 

I can add a new function that draws an element on screen with that. It should work with the bootstrap js files. The implementation would need to be tested.

**Comment by 7sharp9** [comment]
I thought there might be some combination of attributes passed to the Bootstrap.button/nav functions

**Comment by rowpsmo1859** [comment]
Oh yes that could work as well.

The code would look like

```
btn BtnPrimary [ BtnBlock, BtnLarge ] [ attribute "data-toggle" "collapse" ] [ text "Hello world!" ]

div [ class "collapse" ] 
 [
  h2 [] [ text "Hello world" ]
 ]

```

**Comment by rowpsmo1859** [comment]
I added a button modifier type to pass to the btn function

Upgrade to 6.0.0 then change the btn function like so

```
btn BtnPrimary [ BtnBlock, BtnLarge ] [ BtnCollapse "#idOfElement, .orClass" ] [] [ text "Hello world!" ]
```

That should add the necessary attributes. 

http://package.elm-lang.org/packages/JeremyBellows/elm-bootstrapify/6.0.0/Bootstrap-Buttons#ButtonModifier

**Comment by 7sharp9** [comment]
Does the modifier need to be a list?
Possibly an empty list is better than a `Nothing maybe` though.

**Comment by rowpsmo1859** [comment]
It doesn't  have to be right now. It may be useful to add more button modifiers in the future (to accommodate the rest of the attributes from https://getbootstrap.com/javascript/#buttons)
